pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-git
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Git
  desc: Clones a git repository
  type: clone
  image: plugins/drone-git
  labels:
    - scm
    - vcs
    - git

